### ISSUE TITLE
My life is forever changed

### ISSUE THREAD

**Issue by jayaram-karthik** [cubedhuang/college-board-pseudocode-interpreter#1]
Ever since I saw this repo, I can't stop writing collegeboard pseudocode. It started off as a minor addiction, I would code in it for 5 hours a day, but now it has gone too far. I rewrote the entire linux kernel and recreated every algorithm ever created in this amazing language. I love collegeboard so much as they are a very non corrupt non money hungry organization. This language has changed my life. I left my romantic partner just so I could go and live in an upstate new york apartment and fantasize about my time with this language. This language has made it so I will never touch grass again. Please send help.

Sincerely,
Mlon Eusk

**Comment by cubedhuang** [comment]
Won't fix,
